let
    Source = Excel.Workbook(File.Contents("C:\Users\91703\Desktop\DATA BY SANTHOSH\EmployeeData.xlsx"), null, true),
    EmployeeData1_Sheet = Source{[Item="EmployeeData1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(EmployeeData1_Sheet, [PromoteAllScalars=true]),
    #"change emp data1 as emp" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", Int64.Type}, {"NationalIDNumber", Int64.Type}, {"ContactID", Int64.Type}, {"LoginID", type text}, {"ManagerID", Int64.Type}, {"Title", type text}, {"BirthDate", type datetime}, {"MaritalStatus", type text}, {"Gender", type text}, {"HireDate", type datetime}, {"Dept", type text}, {"Salary", Int64.Type}, {"Job Grade", type text}, {"CurrentFlag", Int64.Type}, {"rowguid", type text}}),
    #"removed flag,loginid,nationalid,contactid" = Table.RemoveColumns(#"change emp data1 as emp",{"NationalIDNumber", "ContactID", "LoginID", "ManagerID", "CurrentFlag", "rowguid"}),
    #"Split title Column by Delimiter" = Table.SplitColumn(#"removed flag,loginid,nationalid,contactid", "Title", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.None, false), {"Title.1", "Title.2"}),
    #"title as first name,last name" = Table.RenameColumns(#"Split title Column by Delimiter",{{"Title.1", "First name"}, {"Title.2", "Last name"}}),
    #"changed birthdate to date" = Table.TransformColumnTypes(#"title as first name,last name",{{"BirthDate", type date}}),
    #"Replaced M as married" = Table.ReplaceValue(#"changed birthdate to date","M","Married",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replaced S as single" = Table.ReplaceValue(#"Replaced M as married","S","Single",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replaced M as Male" = Table.ReplaceValue(#"Replaced S as single","M","Male",Replacer.ReplaceText,{"Gender"}),
    #"Replaced F as female" = Table.ReplaceValue(#"Replaced M as Male","F","Female",Replacer.ReplaceText,{"Gender"}),
    #"Changed hiredate to date" = Table.TransformColumnTypes(#"Replaced F as female",{{"HireDate", type date}}),
    #"Changed Type" = Table.TransformColumnTypes(#"Changed hiredate to date",{{"Title.1", type text}, {"Title.2", type text}})
in
    #"Changed Type"